ss = set(range(-9,10,1))
pp = set(range(-4,5,1))
qq = set(range(-7,2,1))
rr = set(range(-1,8,1))
print('S:',ss)
print('P:',pp)
print('Q:',qq)
print('R:',rr)
print('\n')
print('Tentukan P gabungan Q')
print(pp.union(qq))
print('\n')
print('Tentukan P gabungan R')
print(pp.union(rr))
print('\n')
print('Tentutkan Q gabungan R')
print(qq.union(rr))